version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb-weffs
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
